error-channel = "#alpha_uhoh"
mute-role = "Muted"

[[selfrole]]
mode = "command"
channel = "bot-spam" # or channel id
emoji = ":angy:" # or emoji id
roles = [ 604116331356487680 ]
opt-in = true
opt-out = true

[[selfrole]]
mode = "button"
channel = 604116058407829506 # or channel name
emoji = 828434317461815327 # or emoji name
role = "Early Supporter"
opt-in = true
opt-out = false

[[selfrole]]
mode = "reaction"
message = "https://canary.discord.com/channels/604085864514977813/604116058407829506/849413621485404190"

[[group]]
name = "mods"
roles = [ "Moderators", 604116331356487680 ]
members = [ "IAmTomahawkx#1000", 828434317461815327 ]

[[counter]]
name = "warnings"
per-user = true
initial-count = 0
decay = "1/30d"

[[event]]
name = "warn"
actions = [
    { counter = "warnings", modify = 1, target = "$userid" },
    { dispatch = "kick", if = "%warnings($userid) == 5", args = { context = "Automatic kick for having 5 warnings"}},
    { dispatch = "ban", if = "%warnings($userid) >= 10", args = { context = "Automatic ban for having 10 warnings"}}
]

[[event]]
name = "pardon"
actions = [
    { counter = "warnings", modify = -1, target = "$userid" }
]

[[event]]
name = "kick"
actions = [
    { do = "$kick($userid, $context)" } # kick/ban/mute will automatically create a new case. No need to make one yourself!
]

[[event]]
name = "ban"
actions = [
    { do = "$ban($userid, $context)" } # This will also automatically create a new case.
]

[[logging]]
name = "public-log"
channel = "#logs" # or channel id
format = "$target \\($target\\) was $action ed by $user \\($userid\\) in $channel \\($channelid\\) for reason: $reason"

[[logging]]
name = "mod-log"
channel = 604436920843501568
format.kick = "$user was kicked by $mod for reason: `$reason`"
format.ban = "$user was banned by $mod for reason: `$reason`"
format.warn = "$user was warned by $mod for reason: `$reason`"
format.history-join = "$target has joined. They have more than 5 previous cases"

[[command]]
name = "warn"
group = "mods"
arguments = [
    { name = "target", type = "user" },
    { name = "reason", type = "text" } # last argument will always get the full remaining text
]
actions = [
    { do = "$savecase($targetid, $authorid, $reason, $messagelink, 'warn')" },
    { dispatch = "warn", args = { reason = "$reason", target = "$targetname", targetid = "$targetid" } },
    { reply = "Warned $targetname" }
]

[[automod]]
event = "member_join"
ignore = { roles = ["developer", 604125833405136897], channels = [604436940581896241, "logs", "#join-and-leave"] }
actions = [
    { log = "mod-log", event = "history-join", if = "$casecount($userid) >= 5" }
]