error-channel = "#errors"
mute-role = "Muted"

[[counter]]
name = "spam"
per-user = true
initial-count = 0
decay = "5/5s"
# it is important to note that anything faster than 5 seconds won't work,
# as decay is calculated at a maximum every 5 seconds

[[automod]]
event = "message"
actions = [
    { counter = "spam", modify = 1, target = "$userid" },
    { do = "$mute($userid, 'Spamming messages', '10 minutes')", if = "%spam($userid) > 5" }
]