[package]
name = "safe_regex"
version = "0.1.0"
authors = ["IAmTomahawkx <iamtomahawkx@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "safe_regex"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.13.2", features = ["extension-module"] }
regex = "1.5.4"
